// AUTO-GENERATED by scripts/gen-mdx-types.ts — DO NOT EDIT
// Regenerate: bun scripts/gen-mdx-types.ts
//
// Typed declarations for 11 MDX prompt files.
// Props extracted from remark-mdx AST expression nodes,
// so `tsc --noEmit` catches wrong names, missing props, and extras.

declare module "*/prompts/BuildVerify.mdx" {
  interface BuildVerifyPromptProps {
    buildSteps?: any;
    filesCreated?: any;
    filesModified?: any;
    fixCommitPrefix?: any;
    projectName: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
    whatWasDone?: any;
  }
  const Component: import("react").FC<BuildVerifyPromptProps>;
  export default Component;
}

declare module "*/prompts/CodeReview.mdx" {
  interface CodeReviewPromptProps {
    filesCreated?: any;
    filesModified?: any;
    qualityChecks?: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
  }
  const Component: import("react").FC<CodeReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/Discover.mdx" {
  interface DiscoverPromptProps {
    categories: any;
    completedTicketIds?: any;
    existingTickets?: any;
    previousProgress?: any;
    projectName: any;
    referenceFiles: any;
    reviewFindings?: any;
    specsPath: any;
  }
  const Component: import("react").FC<DiscoverPromptProps>;
  export default Component;
}

declare module "*/prompts/Implement.mdx" {
  interface ImplementPromptProps {
    architectureRules?: any;
    commitPrefix?: any;
    contextFilePath: any;
    emojiPrefixes?: any;
    evictionContext?: any;
    failingTests?: any;
    formatterCommands?: any;
    implementationGuidance?: any;
    implementationSteps?: any;
    planFilePath: any;
    previousImplementation?: any;
    reviewFeedback?: any;
    testWritingGuidance?: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
    verifyCommands?: any;
  }
  const Component: import("react").FC<ImplementPromptProps>;
  export default Component;
}

declare module "*/prompts/Plan.mdx" {
  interface PlanPromptProps {
    acceptanceCriteria?: any;
    commitPrefix?: any;
    contextFilePath: any;
    evictionContext?: any;
    planFilePath: any;
    researchSummary?: any;
    tddPatterns?: any;
    ticketCategory: any;
    ticketDescription: any;
    ticketId: any;
    ticketTitle: any;
  }
  const Component: import("react").FC<PlanPromptProps>;
  export default Component;
}

declare module "*/prompts/Report.mdx" {
  interface ReportPromptProps {
    acceptanceCriteria?: any;
    allIssuesResolved: any;
    codeSeverity: any;
    reviewRounds: any;
    specSeverity: any;
    testResults?: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
  }
  const Component: import("react").FC<ReportPromptProps>;
  export default Component;
}

declare module "*/prompts/Research.mdx" {
  interface ResearchPromptProps {
    contextFilePath: any;
    evictionContext?: any;
    referenceFiles?: any;
    referencePaths?: any;
    relevantFiles?: any;
    ticketCategory: any;
    ticketDescription: any;
    ticketId: any;
    ticketTitle: any;
  }
  const Component: import("react").FC<ResearchPromptProps>;
  export default Component;
}

declare module "*/prompts/ReviewFix.mdx" {
  interface ReviewFixPromptProps {
    codeFeedback: any;
    codeIssues?: any;
    codeSeverity: any;
    commitPrefix?: any;
    emojiPrefixes?: any;
    specFeedback: any;
    specIssues?: any;
    specSeverity: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
    validationCommands?: any;
  }
  const Component: import("react").FC<ReviewFixPromptProps>;
  export default Component;
}

declare module "*/prompts/SpecReview.mdx" {
  interface SpecReviewPromptProps {
    failingSummary?: any;
    filesCreated?: any;
    filesModified?: any;
    specChecks?: any;
    testResults?: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
  }
  const Component: import("react").FC<SpecReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/Test.mdx" {
  interface TestPromptProps {
    fixCommitPrefix?: any;
    testSuites?: any;
    ticketCategory: any;
    ticketId: any;
    ticketTitle: any;
  }
  const Component: import("react").FC<TestPromptProps>;
  export default Component;
}

declare module "*/prompts/UpdateProgress.mdx" {
  interface UpdateProgressPromptProps {
    commitMessage?: any;
    completedTickets?: any;
    progressFile: any;
    projectName: any;
  }
  const Component: import("react").FC<UpdateProgressPromptProps>;
  export default Component;
}
